using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdminPanel.Entity;

/// <summary>
/// Represents a comment entity.
///
/// Properties:
/// - Id (Guid): Required, unique identifier, generated by the database.
/// - Name (string): Required. The name of the commenter.
/// - Body (string): Required. The content of the comment.
/// - ParentCommentId (Guid?): Optional. The ID of the parent comment if it's a reply.
/// - GameId (Guid): Required. The ID of the associated game.
/// </summary>
public class CommentEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }

    public string Name { get; set; }

    [Required]
    public string Body { get; set; }

    public Guid? ParentCommentId { get; set; }

    [Required]
    public Guid GameId { get; set; }
}
